name: GitHub Actions Demo
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello GitHub Actions!"

      - name: Print Date
        run: date

      - name: Print Current Directory
        run: pwd

      



        
    
